services:
  gold-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GOLD_API_KEY=${GOLD_API_KEY}
      - SECRET_KEY=change_this_to_a_random_string
    volumes:
      - ./:/app
      - gold_data:/app/data
    restart: unless-stopped

volumes:
  gold_data:
    # This creates a named volume that persists even if containers are removed
